### ISSUE TITLE
动态New的时候有点问题

### ISSUE THREAD

**Issue by SomnusWu** [niniloveyou/DrawableTextView#1]
DrawableTextView mDrawableTextView = new DrawableTextView(this);
        mDrawableTextView.setLayoutParams(new ViewGroup.LayoutParams(ViewGroup.LayoutParams.WRAP_CONTENT, ViewGroup.LayoutParams.WRAP_CONTENT));
        mDrawableTextView.setDrawable(DrawableTextView.RIGHT, ContextCompat.getDrawable(this, R.mipmap.ic_launcher), dip2px(this, 10), dip2px(this, 10));
        mDrawableTextView.setText("帖子");
        mContentView.addView(mDrawableTextView);

会出现显示不全。

**Comment by niniloveyou** [comment]
能截个图吗？ 我这边跑了一下这段代码，显示没问题 @SomnusWu

**Comment by SomnusWu** [comment]
![image](https://cloud.githubusercontent.com/assets/7221064/26230934/fd0f85a6-3c7e-11e7-8fc9-27c0b87fc732.png)
![image](https://cloud.githubusercontent.com/assets/7221064/26230953/1bd4154c-3c7f-11e7-9405-5700bf27eb6f.png)

**Comment by niniloveyou** [comment]
![wx20170519-175455](https://cloud.githubusercontent.com/assets/7897490/26242820/57d3ed00-3cbc-11e7-9d8f-5b8d7c2b9c18.png)

我把这段代码也上传到demo的MainActivity了，你看看，这样显示反而是对的，，， @SomnusWu

**Comment by SomnusWu** [comment]
![s](https://cloud.githubusercontent.com/assets/7221064/26290088/782cf548-3ed7-11e7-9b99-29d403f9fc59.png)


那没有达到 drawableLeft  Right的效果 额 。
